name: regenerating the latest/min-variant-tree.txt 

on:
  push:
    branches: 
      - main
  schedule:
      - cron: '20 0 * * *'
  workflow_dispatch:
          branches: [ main ]

jobs:
  generate-latest-min-tree:
    runs-on: ubuntu-latest

    steps:
      - name: Set variables
        run: |
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "json_tree=https://raw.githubusercontent.com/MDU-PHL/pango-watch/main/tree/data.json" >> $GITHUB_ENV
        shell: bash

      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate
        run: |
          mkdir -p latest
          curl --silent --show-error --location ${json_tree} >latest/data.json
          perl pretty-tree.pl latest/data.json >latest/min-variant-tree.txt
          rm latest/data.json
          grep "BA\.5\.2" latest/min-variant-tree.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "janko-js"
          git config --global user.email "116484385+janko-js@users.noreply.github.com"
          if [ "$(git status --porcelain | head -1)" ]
          then
            git add -A
            git commit -m "update $TAG_NAME"
            git push
          fi
