name: regenerating the latest/min-variant-tree.txt 

on:
  push:
    branches: 
      - main
  schedule:
      - cron: '20 0 * * *'
  workflow_dispatch:
          branches: [ main ]

jobs:
  generate-latest-min-tree:
    runs-on: ubuntu-latest

    steps:
      - name: Set variables
        run: |
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TREE_REMOTE=https://raw.githubusercontent.com/MDU-PHL/pango-watch/main/tree/data.json" >> $GITHUB_ENV
          echo "INPUT=latest/data.json" >> $GITHUB_ENV
          echo "RESULT=latest/min-variant-tree.txt" >> $GITHUB_ENV
        shell: bash

      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch remote tree, generate result
        run: |
          echo Fetching remote tree from $TREE_REMOTE to $INPUT then processing it to $RESULT 
          mkdir -p latest
          curl  --fail --silent --show-error --location $TREE_REMOTE >$INPUT
          perl pretty-tree.pl $INPUT >$RESULT
          rm $INPUT
          grep -c "BA\.5\.2" $RESULT
        shell: bash

      - name: If result differs, push it
        run: |
          echo If $RESULT is changed push
          git config --global user.name "$GITHUB_REPOSITORY_OWNER"
          git config --global user.email "${{github.repository_owner_id}}+$GITHUB_REPOSITORY_OWNER@users.noreply.github.com"
          if [ "$(git status --porcelain $RESULT | head -1)" ]
          then
            echo Adding $RESULT
            git add $RESULT
            echo Commiting
            git commit -m "update $TAG_NAME"
            echo Pushing
            git push
            echo Done.
          else
            echo Nothing to do.
            true
          fi
        shell: bash
