name: regenerating the latest/min-variant-tree.txt 

on:
  push:
    branches: 
      - main
  schedule:
      - cron: '20 0 * * *'
  workflow_dispatch:
          branches: [ main ]

jobs:
  try-curl-1:
    runs-on: ubuntu-latest

    steps:
      - name: Set variables
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "json_tree=https://raw.githubusercontent.com/MDU-PHL/pango-watch/main/tree/data.json" >> $GITHUB_ENV
        shell: bash

      - name: Checkout the main
        uses: actions/checkout@v3

      - name: Generate one more line
        run: |
          mkdir -p latest
          curl --silent --show-error --location ${json_tree} > data.json
          perl pretty-tree.pl >latest/min-variant-tree.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "janko-js"
          git config --global user.email ""
          if [ "$(git status --porcelain | head -1)" ]
          then
            git add -A
            git commit -m "update $TAG_NAME"
            git push
          fi
